import Metadata from './Metadata';
import ManyGameCharacters from './autogenerated/ManyGameCharacters';

export default class MetadataStore {
    metadata: Metadata[];

    constructor() {
        this.metadata = [
            ManyGameCharacters
        ];
    }
};